// This file can be replaced during build by using the `fileReplacements` array.
// `ng build --prod` replaces `environment.ts` with `environment.prod.ts`.
// The list of file replacements can be found in `angular.json`.

export const environment = {
  production: false,
  baseUrl: 'http://localhost:8088',
  proba: "proba",
  medication: "medication",
  findAll: "findAll",
  add: "add",
  ingredients: "ingredients",
  allergy : "allergies",
  patient : "patient",
  register : "register",
  authenticate: 'authenticate',
  getUser: 'getUser',
  login:"login",
  admin:"admin",
  pharmacy : "pharmacy",
  pharmacyAdmin:"pharmacyAdmin",
  dermatologist : "dermatologist",
  supplier : "supplier",
  auth:"auth",
  getById: "getById",
  update : "update",
  editPatient: "editPatient",
  getLoggedInUser: "getLoggedIn",
  reservations : "reservations",
  getReservations : "getReservations",
  changepassword : "changepassword",
  getDermatologistToComplain : "getDermatologistToComplain",
  pharmacist:"pharmacist",
  getPharmacistToComplain : "getPharmacistToComplain",
  complaint:"complaint",
  getPharmacyToComplain : "getPharmacyToComplain",
  getUnanswered:"getUnanswered",
  answerComplaint : "answerComplaint",
  getUnansweredDermatologist : "getUnansweredDermatologist",
  getUnansweredPharmacist : "getUnansweredPharmacist",
  getUnansweredPharmacy : "getUnansweredPharmacy",
  order: "order",
  offer : "offer",
  findSuppliers : "findSuppliers",
  getByIdentifier : 'getByIdentifier',
  getOrderedMedicationByIdentifier : 'getOrderedMedicationByIdentifier',
  pharmacyStorage:'pharmacyStorage',
  getMedicationsInPharmacy:'getMedicationsInPharmacy',
  suppliersmedications : "suppliersmedications",
  getByMedication : "getByMedication",
  getByName:"getByName",
  findByMedication : "findByMedication",
  getByIds : "getByIds",
  pricelist : "pricelist",
  getByType : "getByType",
  getByForm : "getByForm",
  getByKind : "getByKind",
  getByPrescribing : "getByPrescribing",
  activation : "activation",
  subscribe : "subscribe",
  isSubscribed : "isSubscribed",
  getAllUsers : "getAllUsers",
  remove: "remove",
  getSubscribed : "getSubscribed",
  getByStatus: "getByStatus",
  getAllOrdersWehereOfferIsNotGivenBySupplier :"getAllOrdersWehereOfferIsNotGivenBySupplier",
  getByPharmacy:"getByPharmacy",
  medicalRecord : "medicalRecord",
  getPatientIngredients : "getPatientIngredients",
  addPatientIngredient : "addPatientIngredient",
  updateEmployees : "updateEmployee",
  changeEmployeePass : "changeEmployeePass",
  firstTimePasswordChange : "firstEmployeeLogin",
  appointment : "appointment",
  getPatientsByMedicalStaff : "getPatientsByMedicalStaff",
  searchPatients : "searchPatients",
  findReservations : "getReservationByIdentifier",
  issueReservation : "issueReservation",
  scheduledAppointments : "getScheduledByDateAndStaff",
  findAvailableForEmployee : "getAppointmentsForEmployee",
  medicalRecord : "medicalRecord",
  recommendMedications : "recommendMedicationByPatient"

};

